version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "project-team-kat/paymates-backend"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "project-team-kat/paymates-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend:be"