version: '3'

services:
  backend:
    env_file:
        "./backend/.env"
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    image: "project-team-kat/paymates-backend"
    ports:
      - "8000:8000"
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"
